language: python
dist: xenial
sudo: true

python:
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - DJANGO_SETTINGS_MODULE="settings"
    - PYTHONPATH="/home/travis/build/sbywater/django-asana"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO_VERSION="django>=1.9,<1.10"
    - DJANGO_VERSION="django>=1.10,<1.11"
    - DJANGO_VERSION="django>=1.11,<1.12"
    - DJANGO_VERSION="django>=2.0,<2.1"
    - DJANGO_VERSION="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - DJANGO_VERSION="https://github.com/django/django/archive/master.tar.gz"

install:
  - pip install $DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install .

script:
  - coverage run manage.py test

after_success:
  - coveralls
