# Generated by Django 2.1 on 2018-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0007_adds_gid'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='project',
        #     name='start_on',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='story',
        #     name='is_edited',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='story',
        #     name='is_pinned',
        #     field=models.BooleanField(default=False),
        # ),
    ]
