# Generated by Django 2.1 on 2018-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0006_auto_20180819_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
