# Generated by Django 2.1 on 2018-09-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0007_auto_20180819_1518'),
    ]

    operations = [

        migrations.AlterField(
            model_name='customfield',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='enum_options',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
