# Generated by Django 2.1 on 2018-09-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0008_auto_20180906_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='target',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
