# Generated by Django 2.0.6 on 2018-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0015_adds_task_start_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='download_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
