# Generated by Django 2.0.7 on 2018-07-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0016_adds_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
